[project]
name = "usports-basketball"
version = "1.0.0"
description = "A Python package for USports basketball stats."
readme = "README.md"
license = {file = "LICENSE.txt"}
authors = [{name = "OJ Adeyemi", email = "ojieadeyemi@gmail.com"}]
maintainers = [{name = "OJ Adeyemi", email = "ojieadeyemi@gmail.com"}]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
]
requires-python = ">=3.8"
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "pandas>=2.2.0",
]

[build-system]
requires = ["setuptools>=46.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
]
[tool.poetry.group.dev.dependencies]
pytest = "^7.4"

[project.urls]